### ISSUE TITLE
WatchOS app and Custom horn

### ISSUE THREAD

**Issue by ghost** [SvenTiigi/VanMoofKit#1]
### Is your feature request related to a problem?

No

### What solution would you like?

A watchOS app for this project and to know how to add custom horns

### What alternatives have you considered?

-

**Comment by SvenTiigi** [comment]
Hi @TimTheBeast,

The VanMoofKit Swift Package supports the watchOS platform, so you can easily use it to create your own watchOS application.
An option to add a custom horn/bell sound is not technically possible as the VanMoof Bike doesn't provide such an API.

**Comment by ghost** [comment]
is it possible to add a sound that's already on the bike as a horn? And
are you ever going to make an example app for the apple watch?
