### ISSUE TITLE
VanMoof S/A5 Support

### ISSUE THREAD

**Issue by drolpi** [SvenTiigi/VanMoofKit#10]
### Is your feature request related to a problem?

No

### What solution would you like?

Please implement the S/A5 

### What alternatives have you considered?

Not using VanMoofKit? haha no idea

**Comment by SvenTiigi** [comment]
Currently there are no plans in supporting the S/A5 VanMoof Bike mostly because I don't own a model of this bike in order to reverse engineer the bluetooth API and underlying communication data.

Please feel free to open up a PR to get things started.
