### ISSUE TITLE
Issue when logging in

### ISSUE THREAD

**Issue by TimTheBeastNL** [SvenTiigi/VanMoofKit#11]
### What happened?

The first version of my app would be released and then this error occurred. I saw that Moofer also had an update today and previous versions also don't work anymore
![image](https://github.com/SvenTiigi/VanMoofKit/assets/118755239/bc89f8a5-cec9-495f-8df4-d2afbd463dd2)

### What are the steps to reproduce?

This error occurs when logging into your Vanmoof account.

### What is the expected behavior?

it to work

**Comment by SvenTiigi** [comment]
Fixed with the latest release [`0.0.5`](https://github.com/SvenTiigi/VanMoofKit/releases/tag/0.0.5)
