### ISSUE TITLE
Cannot convert return expression of type 'String' to return type 'ImageResource' Error in Xcode

### ISSUE THREAD

**Issue by TimTheBeastNL** [SvenTiigi/VanMoofKit#2]
### What happened?

I get the "Cannot convert return expression of type 'String' to return type 'ImageResource'" error message in Xcode at the part of the light modes in BikeView+LightModeCard.
Here is the error

switch lightMode {
                                    case .auto:
                                          return "LightModeAuto"            Cannot convert return expression of type 'String' to return type 'ImageResource'
                                    case .alwaysOn:
                                        return "LightModeAlwaysOn".     Cannot convert return expression of type 'String' to return type 'ImageResource'
                                    case .off:
                                        return "LightModeOff".     Cannot convert return expression of type 'String' to return type 'ImageResource'

### What are the steps to reproduce?

<img width="1025" alt="Screenshot 2023-06-22 at 7 33 42 AM" src="https://github.com/SvenTiigi/VanMoofKit/assets/118755239/58307a9a-8a31-4fb8-a554-1bc1444883f0">

### What is the expected behavior?

I expect it would work again

**Comment by SvenTiigi** [comment]
Hi @TimTheBeastNL,

Please check out the [develop branch](https://github.com/SvenTiigi/VanMoofKit/tree/develop) which contains a [fix](https://github.com/SvenTiigi/VanMoofKit/commit/cdfe4ec10114abe9a83ed86979da67bac664ec7c) to resolve this issue.
