### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TimTheBeastNL** [SvenTiigi/VanMoofKit#7]
### Is your feature request related to a problem?

I'm making my own app based on the Example app you made, I would love to see these features available :
- Alarm
 Turn the alarm on and off
 When the alarm goes off send a notification to the phone
-Touch Unlock
Allow the bike to unlock using the buttons on the bike
-Shifting
Allow the following Gear shifting modes:
Flat, Hilly, Custom and Manual
-Sounds
Allow to mute wake up and unlocking sound.
Allow custom sounds to be uploaded, this is already a thing on the mooovy.app repo/site, It is also possible to change the sound  by changing the number of the sound for example replacing the foghorn would be 24 and F for the Alarm sound.
- Speed limit:
 Allow 37km/h
 Allow Assist 5
-Buttons
 Allow the get data from the buttons, like boost button pressed once

### What solution would you like?

I would love to see these features available

### What alternatives have you considered?

there aren't any alternatives to consider

**Comment by SvenTiigi** [comment]
Great ideas @TimTheBeastNL, please feel free to open up a PR.
