### ISSUE TITLE
Error when using the app with multiple bikes

### ISSUE THREAD

**Issue by TimTheBeastNL** [SvenTiigi/VanMoofKit#8]
### What happened?

This error message shows up when i open the app, I think it is because there is an S5 of the account, if so Mooovy used this to fix that problem in their code https://github.com/mjarkk/vanmoof-web-controller/commit/8a2bc9779f0fff410aec5e7b06871a4360159396. ![image](https://github.com/SvenTiigi/VanMoofKit/assets/118755239/fbdfdd90-6885-4525-b490-237318731abc)

### What are the steps to reproduce?

Have an account with multiple bikes and with at least 1 S5.

### What is the expected behavior?

I would except VanMoofKit to work with multiple bikes and an s5 on your account. I was also wondering how far you were with developing the custom bell sound feature.

**Comment by SvenTiigi** [comment]
Should be fixed with https://github.com/SvenTiigi/VanMoofKit/commit/d405ccbe7a5faaa303f1d04c7fe15596c2008de0

**Comment by SvenTiigi** [comment]
Fixed with the latest release [`0.0.5`](https://github.com/SvenTiigi/VanMoofKit/releases/tag/0.0.5)
